benchmark: core/native/randomized_benchmarking

benchmark_params: # benchamark specific params
  num_qubits: 2
  lengths: [2, 4, 8, 16]
  num_sequences: 2

adapter: mqss_qiskit
backend: QExa20

credentials:
  mqss_token: ""

shots: 200

output_dir: "./results"

# Controls what is generated
report:
  analysis:
    enabled: true
    visualization:
      enabled: true
      show: true

# Controls how results are persisted
storage:
  type: "file"  # "file" or "sqlite"
  file:
    format: "json"
  sqlite:
    db_path: "./mqssbench.db"
  
profiling:
  enabled: true
  metrics: # not defining metrics means all of them are requested
    - transpiler
    - submitter